//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxconn.Wcf.Client.FoxconnService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Foxconn.Bo")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FoxconnService.IFoxconnService")]
    public interface IFoxconnService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxconnService/GetStudents", ReplyAction="http://tempuri.org/IFoxconnService/GetStudentsResponse")]
        Foxconn.Wcf.Client.FoxconnService.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxconnService/GetStudents", ReplyAction="http://tempuri.org/IFoxconnService/GetStudentsResponse")]
        System.Threading.Tasks.Task<Foxconn.Wcf.Client.FoxconnService.Student[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxconnService/GetStudentByName", ReplyAction="http://tempuri.org/IFoxconnService/GetStudentByNameResponse")]
        Foxconn.Wcf.Client.FoxconnService.Student[] GetStudentByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxconnService/GetStudentByName", ReplyAction="http://tempuri.org/IFoxconnService/GetStudentByNameResponse")]
        System.Threading.Tasks.Task<Foxconn.Wcf.Client.FoxconnService.Student[]> GetStudentByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxconnService/InsertStudent", ReplyAction="http://tempuri.org/IFoxconnService/InsertStudentResponse")]
        void InsertStudent(Foxconn.Wcf.Client.FoxconnService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxconnService/InsertStudent", ReplyAction="http://tempuri.org/IFoxconnService/InsertStudentResponse")]
        System.Threading.Tasks.Task InsertStudentAsync(Foxconn.Wcf.Client.FoxconnService.Student student);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoxconnServiceChannel : Foxconn.Wcf.Client.FoxconnService.IFoxconnService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoxconnServiceClient : System.ServiceModel.ClientBase<Foxconn.Wcf.Client.FoxconnService.IFoxconnService>, Foxconn.Wcf.Client.FoxconnService.IFoxconnService {
        
        public FoxconnServiceClient() {
        }
        
        public FoxconnServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoxconnServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoxconnServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoxconnServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Foxconn.Wcf.Client.FoxconnService.Student[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<Foxconn.Wcf.Client.FoxconnService.Student[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public Foxconn.Wcf.Client.FoxconnService.Student[] GetStudentByName(string name) {
            return base.Channel.GetStudentByName(name);
        }
        
        public System.Threading.Tasks.Task<Foxconn.Wcf.Client.FoxconnService.Student[]> GetStudentByNameAsync(string name) {
            return base.Channel.GetStudentByNameAsync(name);
        }
        
        public void InsertStudent(Foxconn.Wcf.Client.FoxconnService.Student student) {
            base.Channel.InsertStudent(student);
        }
        
        public System.Threading.Tasks.Task InsertStudentAsync(Foxconn.Wcf.Client.FoxconnService.Student student) {
            return base.Channel.InsertStudentAsync(student);
        }
    }
}
