//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxconn.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> TeacherId { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
